### ISSUE TITLE
Bug with $FLAGS ?

### ISSUE THREAD

**Issue by florent26** [gbloquel/puppet-postgres_exporter#2]
Hi,
It seems $FLAGS is missing in systemd config :
<code>
ExecStart=/opt/postgres_exporter_v0.4.6_linux-amd64/postgres_exporter $FLAGS
</code>

Without this config, the FLAGS paramters are ignored ...

Regards,

**Comment by gbloquel** [comment]
Hi @florent26,

Thanks you for your remark. I've fixed it.

Regards,
