### ISSUE TITLE
Upgrade the module to the latest version

### ISSUE THREAD

**Issue by mfuhrmann** [gbloquel/puppet-postgres_exporter#4]
Right now the module is running `postgres_exporter` `0.4.6` which is quite old and does not support the label flags.
I've tried to set a newer version (`0.8.0`) [here](https://github.com/gbloquel/puppet-postgres_exporter/blob/bb84e579563ac9adc38396b6af0cc162d7d14fc6/manifests/init.pp#L17), but the module still installs `0.4.6`.

@gbloquel Can you provide an update here or document what's exactly required to do that?

**Comment by gbloquel** [comment]
Hello @mfuhrmann 
You're right it was a defect with the use of version parameter.

It fixed it.
