### ISSUE TITLE
Enhance template file to support DATA_SOURCE_URI

### ISSUE THREAD

**Issue by mfuhrmann** [gbloquel/puppet-postgres_exporter#6]
How to use `DATA_SOURCE_URI` in the config file?

It looks like `DATA_SOURCE_NAME` is hardcoded here: https://github.com/gbloquel/puppet-postgres_exporter/blob/master/templates/postgres_exporter.configfile.epp#L3
and thus not possible.

But if you want to connect against the socket `postgres_exporter` requires `DATA_SOURCE_URI`.

For example:
`DATA_SOURCE_URI="postgres@:5432/databasename?host=/var/run/postgresql/"`

**Comment by gbloquel** [comment]
Hi Marcel,

As mentioned on postgres_exporter see [https://github.com/prometheus-community/postgres_exporter/blob/v0.8.0/README.md](https://github.com/prometheus-community/postgres_exporter/blob/v0.8.0/README.md)

> DATA_SOURCE_NAME the default legacy format. Accepts URI form and key=value form arguments. The URI may contain the username and password to connect with.
> ...
> For running it locally on a default Debian/Ubuntu install, this will work (transpose to init script as appropriate):
> 
> sudo -u postgres DATA_SOURCE_NAME="user=postgres host=/var/run/postgresql/ sslmode=disable" postgres_exporter

Then you can use `DATA_SOURCE_NAME` to connect through the socket thanks to key=value form arguments.

Regards,

**Comment by mfuhrmann** [comment]
Thanks! I will give it a try!
