### ISSUE TITLE
Migration to Prometheus Community

### ISSUE THREAD

**Issue by timbuchwaldt** [gbloquel/puppet-postgres_exporter#7]
Hey! Thanks for this cool module! 
Upstream has changed the repo to https://github.com/prometheus-community/postgres_exporter and released 0.9.0 since then which sadly also changed the URL slightly (_ vs .).

Would you be willing to update that or would you like a PR for that? :)

**Comment by gbloquel** [comment]
Hi Tim,

Sorry for the late of my answer. 
I fixed your remark.

Regards,
