### ISSUE TITLE
Upgrade this module to use postgres_exporter 0.10.1

### ISSUE THREAD

**Issue by mfuhrmann** [gbloquel/puppet-postgres_exporter#9]
Since there are newer versions of `postgres_exporter`, we probably want to have also this version in Puppet.
https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.1

**Comment by mfuhrmann** [comment]
@gbloquel Do you know how long it takes until I can use this new version in my Puppetfile?
What version number will it be?

`mod 'gbloquel-postgres_exporter',       '1.0.2'`

**Comment by gbloquel** [comment]
Hi @mfuhrmann ,

I have released the version '1.2.0' including your PR.
Thanks you for your PR.
